---
config:
  - action: remove
    parameter: matrix_exclude
    value: [{"ansible-version": "devel", "python-version": "3.9"}]
  - action: add
    parameter: matrix_exclude
    value: [{"ansible-version": "new1", "python-version": "3.9"}, {"ansible-version": "new1", "python-version": "3.10"}]
  - parameter: uses
    job: sanity
    value: ansible-network/github_actions/.github/workflows/sanity.yml@local
  - parameter: pull_request
    value: {"types" : ["new1", "new2"]}
    action: add
    
