name: CI
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - stable-*
    tags:
      - "*"

jobs:
  linters:
    uses: ./.github/workflows/linters.yml # use the callable linters job to run tests
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
  changelog:
    uses: ansible/ansible-content-actions/.github/workflows/changelog.yaml@main
  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@main
  units:
    uses: ansible-network/github_actions/.github/workflows/unit_source.yml@main

  all_green:
    if: ${{ always() }}
    needs:
      - linters
      - ansible-lint
      - sanity
      - units
      - ansible-lint
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.changelog.result }}',
          '${{ needs.linters.result }}',
          '${{ needs.ansible-lint.result }}',
          '${{ needs.sanity.result }}',
          '${{ needs.unit-galaxy.result }}'
          ]) == {'success'}"
