---
- name: Create dynamic dict to be included in the workflow
  ansible.builtin.set_fact:
    modify_uses: |
      {
        "jobs": {
          "{{ config_items[1] }}": {
            "uses": "{{ config_items[0].value }}"
          }
        }
      }
  when:
    - config_items[0].job in data.jobs
    - config_items[0].job == config_items[1]

- name: Final workflow data
  ansible.builtin.set_fact:
    data: "{{ data | combine(modify_uses, recursive=true) }}"
  when:
    - config_items[0].job in data.jobs
    - config_items[0].job == config_items[1]
