---
- name: Create matrix list dynamically for add action
  ansible.builtin.set_fact:
    modify_param_value: "{{ data.jobs[config_items[1]].with[config_items[0].parameter] | from_yaml + config_items[0].value }}"
  when:
    - config_items[1] in data.jobs
    - config_items[0].action == "add"
    - config_items[0].parameter in data.jobs.{{ config_items[1] }}.with
  ignore_errors: true

- name: Create matrix list dynamically for remove action
  ansible.builtin.include_tasks: remove_item.yaml
  vars:
    to_remove: "{{ config_items[0].value }}"
    present_value: "{{ data.jobs[config_items[1]].with[config_items[0].parameter] | from_yaml }}"

  when:
    - config_items[1] in data.jobs
    - config_items[0].action == "remove"
    - config_items[0].parameter in data.jobs.{{ config_items[1] }}.with
  ignore_errors: true

- name: Create dynamic dict to be included in the workflow
  ansible.builtin.set_fact:
    add_config_items: |
      {
        "jobs": {
          "{{ config_items[1] }}": {
            "with": {
              "{{ config_items[0].parameter }}": "{{ modify_param_value }}"
            }
          }
        }
      }
  when:
    - config_items[1] in data.jobs
    - config_items[0].parameter in data.jobs.{{ config_items[1] }}.with
  ignore_errors: true

- name: Final workflow data
  ansible.builtin.set_fact:
    data: "{{ data | combine(add_config_items, recursive=true) }}"
  when:
    - config_items[1] in data.jobs
    - config_items[0].parameter in data.jobs.{{ config_items[1] }}.with
  ignore_errors: true
